config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :studios do
    resources :bookings, only: [:create, :destroy]
    resources :reviews, only: [:new, :create, :index]
  end

  get 'profile/:id', to: 'dashboards#profile', as: :profile
  patch 'bookings/:id/accept', to: 'bookings#accept', as: :accept
  patch 'bookings/:id/decline', to: 'bookings#decline', as: :decline
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :studio
  belongs_to :user
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  AUTHORIZED_RATINGS = (1..5)
  belongs_to :studio
  belongs_to :user
  validates :comment, presence: true
  validates :rating, inclusion: { in: AUTHORIZED_RATINGS }
end

app/models/studio.rb
class Studio < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  belongs_to :user
  has_many_attached :photos
  has_many :bookings, dependent: :destroy
  has_many :reviews

  include PgSearch::Model
  pg_search_scope :search_by_title_and_address,
    against: [ :title, :adress ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :studios, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @booking = Booking.new(booking_params)
    authorize @booking
    @studio = Studio.find(params[:studio_id])
    @booking.studio = @studio
    @booking.user_id = current_user.id
    if @booking.save
      redirect_to studio_path(@studio)
    else
      render "studios/show"
    end
  end

  def accept
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.status = "Accepted"
    @booking.save
    redirect_to profile_path(current_user, anchor: "booking-#{@booking.id}")
  end

  def decline
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.status = "Declined"
    @booking.save
    redirect_to profile_path(current_user, anchor: "booking-#{@booking.id}")
  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.destroy
    if current_user == @booking.user
      redirect_to profile_path(@booking.studio.user)
    else
      redirect_to profile_path(current_user)
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :comment)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
# before_action :find_user, only: [:show, :edit, :update, :destroy]
# before_action :authenticate_user!, except: [:index, :show]

  def profile
    @user = User.find(params[:id])
    authorize @user
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @review = Review.new(review_params)
    authorize @review
    @studio = Studio.find(params[:studio_id])
    @review.studio = @studio
    @review.user_id = current_user.id
    if @review.save
      redirect_to studio_path(@studio)
    else
      render "studios/show"
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/controllers/studios_controller.rb
class StudiosController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    @studios = policy_scope(Studio).order(created_at: :desc)
    # -------------------------- GEOCODER --------------------------------
    @markers = @studios.geocoded.map do |studio|
      {
        lat: studio.latitude,
        lng: studio.longitude,
        info_window: render_to_string(partial: "info_window", locals: { studio: studio }),
        image_url: helpers.asset_url("logo-map.png")
      }
    end
    # --------------------------- SEARCH ---------------------------------
    if params[:query].present?
      sql_query = "title ILIKE :query OR address ILIKE :query"
      @studios = Studio.where(sql_query, query: "%#{params[:query]}%")
    else
      @studios = Studio.all
    end
  end

  def show
    @studio = Studio.find(params[:id])
    @booking = Booking.new
    @review = Review.new
    @reviews = @studio.reviews
    @average_rating = @reviews.average(:rating)
    # je teste la ligne superieure
    authorize @studio
    # -------------------------- CALENDAR --------------------------------
    @dates = @studio.bookings.map do |booking|
      {
        from: booking.start_date,
        to: booking.end_date
      }
    end
  end

  def new
    @studio = Studio.new
    authorize @studio
  end

  def create
    @studio = Studio.new(studio_params)
    authorize @studio
    @studio.user_id = current_user.id
    if @studio.save
      redirect_to studio_path(@studio)
    else
      render :new
    end
  end

  def edit
    @studio = Studio.find(params[:id])
    authorize @studio
  end

  def update
    @studio = Studio.find(params[:id])
    authorize @studio
    @studio.update(studio_params)
    redirect_to studios_path
  end

  def destroy
    @studio = Studio.find(params[:id])
    authorize @studio
    @studio.destroy
    redirect_to studios_path
  end

  private

  def studio_params
    params.require(:studio).permit(:address, :title, :description, :price, :available, photos: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboards/profile.html.erb
<div class="profil-page">
  <div class="banner-small mb-5 profil-page-banner">
    <div class="banner-content" style="padding-left: 75px">
      <h1> This is <%= @user.nickname %> profile </h1>

      <p>Music studios</p>
    </div>
    <img class="avatar-large" alt="avatar-large" src="<%= @user.photo_id_url %>" />
  </div>
  <div style="margin:0 auto;" class=" d-flex justify-content-center">
    <p class="mt-4"><%= @user.bio %></p>
  </div>


<%# --------------------liste des studios----------------------------------- %>
  <div class="container">
    <% @user.studios.each do |studio| %>
      <div class="m-5 border">
      <%# ---------------- image de la card ----------------%>
        <%= link_to studio_path(studio), class:"link-without-style" do  %>
          <% if studio.photo_url.nil? && studio.photos.attached? %>
            <% url = cl_image_path studio.photos.first.key %>
          <% elsif studio.photo_url.nil? && !studio.photos.attached? %>
           <% url = "https://images.unsplash.com/photo-1560844915-bb3189e146ec?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1863&q=80"%>
          <% else  %>
            <% url = studio.photo_url %>
          <% end %>
      <%# ---------------- contenu de la card ----------------%>

          <div class="card-category mb-5" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= url %>)">
            <h2 class="title-studio-card" > <%= studio.title %> </h2>
            <p class="card-studio-description"> <%= studio.address %> </p>
          </div>
        <% end %>

      <%# ---------------- bookings du studio ----------------%>
      <%# --- seulement visible si c'est mon studio --------%>
        <% if current_user == @user%>
          <% studio.bookings.order(:user_id).each do |booking| %>
            <% if booking.status ==  "Accepted" %>
              <% color="background-color:#B7E4C7;" %>
            <% elsif booking.status ==  "Declined" %>
              <% color="background-color:#F4978E;" %>
            <% else %>
              <% color="background-color:#BCB8B1;" %>
            <% end %>
            <div class="ms-3">
              <div class="bookings-profile-card m-2 d-flex justify-content-between" style="<%= color %>">
                <div class="pt-3" id="booking-<%= booking.id %>">
                  <p>Booking from: <%= booking.user.nickname %>  || email: <%= booking.user.email  %></p>
                  <p>From: <%= booking.start_date  %> To: <%= booking.end_date  %> </p>
                  <p>Comment: <%= booking.comment  %></p>
                  <p><%= booking.studio.price %>€/day for <%= (booking.end_date-booking.start_date).to_i %> days = <%= (booking.end_date - booking.start_date).to_i * booking.studio.price %>€</p>
                  <p>This booking is: <%= booking.status  %></p>
                </div>
                <div>
                  <% if booking.status == "Pending" %>
                    <p> <%= link_to accept_path(booking), remote: true, class:"link_to", method: :patch do %> <i class="fas fa-check"></i></p><% end %>
                    <p> <%= link_to decline_path(booking), remote: true, class:"link_to", method: :patch do %><i class="fas fa-times"></i></p><% end %>
                    <p><%= link_to studio_booking_path(studio), remote: true, class:"link_to", method: :delete, data: { confirm: "Are you sure?" } do %><i class="fas fa-trash-alt"></i></p><% end %>
                  <% elsif booking.status == "Accepted" %>
                    <p> <%= link_to decline_path(booking), remote: true, class:"link_to", method: :patch do %><i class="fas fa-times"></i></p><% end %>
                    <p><%= link_to studio_booking_path(studio, booking), remote: true,class:"link_to", method: :delete, data: { confirm: "Are you sure?" } do %><i class="fas fa-trash-alt"></i></p><% end %>
                  <% else %>
                    <p> <%= link_to accept_path(booking), remote: true, class:"link_to", method: :patch do %> <i class="fas fa-check"></i></p><% end %>
                    <p><%= link_to studio_booking_path(studio, booking), remote: true, class:"link_to", method: :delete, data: { confirm: "Are you sure?" } do %><i class="fas fa-trash-alt"></i></p><% end %>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>

        <%# ---------------- bookings du studio ----------------%>
        <%# --- seulement visible si c'est mon booking --------%>

        <% studio.bookings.each do |booking| %>
          <% if current_user == booking.user %>
            <% if booking.status ==  "Accepted" %>
              <% color="background-color:#B7E4C7;" %>
            <% elsif booking.status ==  "Declined" %>
              <% color="background-color:#F4978E;" %>
            <% else %>
              <% color="background-color:#BCB8B1;" %>
            <% end %>
            <div class="bookings-profile-card m-2 border d-flex justify-content-between" style="<%= color %>">
              <div>
                <p>You booked this studio</p>
                <p>From: <%= booking.start_date  %> To: <%= booking.end_date  %> </p>
                <p>Comment: <%= booking.comment  %></p>
                <p>This booking is: <%= booking.status  %></p>
              </div>
              <div>
                <p><%= link_to studio_booking_path(studio, booking), class:"link_to", method: :delete, data: { confirm: "Are you sure?" } do %><i class="fas fa-trash-alt"></i></p><% end %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>On Air Studio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>

    <%= render 'shared/flashes' %>

    <div class="footer mt-5">
      <div class="d-flex">
        <div class="footer-links">
          <a href="https://github.com/Pyh0rns/rails-airbnb-clone"><i class="fab fa-github"></i></a>
          <a href="#"><i class="fab fa-instagram"></i></a>
        </div>
        <div class="footer-links">
          <a href="#"><i class="fab fa-twitter"></i></a>
          <a href="#"><i class="fab fa-linkedin"></i></a>
        </div>
        <div class="footer-links">
          <a href="#"><i class="fab fa-facebook"></i></a>
        </div>
      </div>

      <div class="infos">
        <h3>Who we are?</h3>
          <a href="">Contact us</a>
          <a href="">General Conditions</a>
      </div>

      <div class="infos">
        <h3> Be part of the adventure!</h3>
          <a href="">Rent your studio</a>
          <a href="">Book a studio</a>
      </div>

       <div class="infos">
        <h3> Candidate</h3>
          <a href="">Send your resume</a>
          <a href="">Candidate Profile</a>
      </div>

      <div class="footer-copyright">
       <p>This footer is made with <i class="fas fa-heart"></i> at Le Wagon</p>
      </div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-background" style="background-image: url('https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80')">
  <div class="home-content d-flex flex-column align-items-center">
    <h1 class="mb-2"><span data-controller="typed-js"></span></h1>
    <%= form_tag studios_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control-landing",
        placeholder: "Enter in the studios"%>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
    <% if notice %>
      <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= notice %>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= alert %>
      </div>
    <% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <div>
      <%= link_to "/studios", class: "navbar-brand" do %>
        <%= image_tag "logo.png" %>
        <h1>Studio</h1>
      <% end %>
    </div>
    <div class="d-flex align-items-center">
      <%= link_to "Post Studio", new_studio_path, class: "navbar-wagon-button btn "%>
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
                    <%#= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>

          <%= image_tag current_user.photo_id_url, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to "My profile", profile_path(current_user), class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "link-white" %>
        </li>
      <% end %>
    </div>
  </div>
</div>

app/views/studios/_form.html.erb
  <%= simple_form_for @studio do |f| %>
    <%= f.input :title %>
    <%= f.input :description, input_html: {class:"input"} %>
    <%= f.input :address,
        input_html: { data: { geocoder_target: "address" }, class: "d-none" },
        wrapper_html: { data: { controller: "geocoder", geocoder_api_key_value: ENV['MAPBOX_API_KEY'] } } %>
    <%= f.input :price %>
    <%= f.input :photos, as: :file, input_html: { multiple: true }%>
    <%= f.input :available %>
    <%= f.button :submit, class: "btn btn-blue"%>
  <% end %>

app/views/studios/_info_window.html.erb
<%= link_to studio_path(studio), class:"text-decoration-none" do %>
  <h2><%= studio.title %></h2>
<% end %>
<p><%= studio.address %></p>

app/views/studios/edit.html.erb
<%= render 'form', studio: @studio %>

app/views/studios/index.html.erb
<div class="banner-small mb-5" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80);">
  <div class="banner-content" style="padding-left: 75px">
    <h1>Visit our studios !</h1>
    <p>And play music</p>
    <%= link_to 'Add your music studio', new_studio_path, class:"linkto btn-transparent-white"  %>
  </div>
</div>

<%# ---------------------------- Search BAR------------------------------ %>
<div class="container">
  <div class="m-5">
    <div>
      <%= form_tag studios_path, class:"input-group", method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control mb-3",
          placeholder: "Find a place to play"
        %>
      <div class="input-group-append">
        <button type="submit" class="btn btn-primary">
          <i class="fas fa-search"></i>
        </button>
      </div>
      <% end %>
    </div>

    <%# ---------------------------- CARDS STUDIOS ------------------------------ %>

    <div class="d-flex" >
      <div class="cards-grid">
        <% @studios.each do |studio| %>
          <%= link_to studio_path(studio), class:"link-without-style" do  %>
            <% if studio.photo_url.nil? && studio.photos.attached? %>
              <% @url = cl_image_path studio.photos.first.key %>
            <% elsif studio.photo_url.nil? && !studio.photos.attached? %>
              <% @url = "https://images.unsplash.com/photo-1560844915-bb3189e146ec?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1863&q=80"%>
            <% else  %>
              <% @url = studio.photo_url %>
            <% end %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= @url %>)">
            <div class="title-studio-card">
              <h2 > <%= studio.title %> </h2>
            </div>

            <div class="card-studio-description">
              <p class="address"><%= studio.address %></p>
            <div class="d-flex justify-content-between mt-auto">
              <p> <strong> <%= studio.user.nickname %> </strong></p>
              <p><%= studio.price%> €/day</p>
            </div>
            </div>
          </div>
          <% end %>
        <% end %>
      </div>

      <%# ------------------------------- GEOCODER -------------------------------- %>
      <div id="map">
        <div class="" style="width: 100%; height: 600px;"
          data-controller="mapbox"
          data-mapbox-markers-value="<%= @markers.to_json %>"
          data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/studios/new.html.erb
<div class="banner-small mb-5" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1518972559570-7cc1309f3229?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80);">
  <div class="banner-content" style="padding-left: 75px">
    <h1>Create a new studio</h1>
    <p>Let's play music !</p>
    <%= link_to 'Back to studios', studios_path, class:"linkto btn-transparent-white" %>
  </div>
</div>

<div class="container d-flex justify-content-center">
  <div class="form">
    <%= render 'form', studio: @studio %>
  </div>
</div>

app/views/studios/show.html.erb
<div class="banner-small mb-5"
  <%# banner: soit photo cloudinary, soit photo_url seed soit photo par defaut %>
    <% if @studio.photo_url.nil? && @studio.photos.attached? %>
      <% url = cl_image_path @studio.photos.first.key %>
    <% elsif @studio.photo_url.nil? && !@studio.photos.attached? %>
      <% url = "https://images.ctfassets.net/anpxw7hl9rcg/6i3V4opLFffyrrG6WoCYsP/f9fdb70e292ce2969d8021a0632afb82/_10_gargolandia.jpg"%>
    <% else  %>
      <% url = @studio.photo_url %>
    <% end %>
      style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= url %>);">

<div class="container">
  <div class="d-flex justify-content-start align-items-center">
    <h1 class="me-2"><%= @studio.title  %></h1>

    <div class="d-flex ml-3">
    <% @totalrating = 0 %>
    <%if @studio.reviews.length >= 1 %>
      <% @studio.reviews.each do |review| %>
        <% @totalrating += review.rating %>
      <% end %>

      <% @average2 = (@totalrating.fdiv(@studio.reviews.length)).round(1) %>
      <% @average = @totalrating / @studio.reviews.length %>
      <% @average.round.times do %>
        <i class="fas fa-star ml-1"></i>
      <% end %>
      <% if (@average) < 5 %>
        <% (5 - @average.round).times do %>
          <i class="far fa-star ml-1"></i>
        <% end %>
      <% end %>
    <% end %>
    </div>
    </div>
    <h1>By: <%= @studio.user.nickname %></h1>
    <img class="avatar-show" src="<%=@studio.user.photo_id_url%>" alt="">
    <%= link_to 'Visit Profil', profile_path(@studio.user.id), class:"btn btn-blue" %>
</div>
</div>


<%# ------------------------- TITRE ET DESCRIPTION -------------------------- %>
<div class="container">
  <div class="studioinfos">
    <h2 class="d-flex justify-content-center"> <strong> <%= @studio.title %></strong></h2>
    <p class="d-flex justify-content-center mt-3"> <%= @studio.description %></p>
  </div>
</div>

<%# -------------- CAROUSEL PHOTOS STUDIO si photos cloudi >= 3 -------------- %>
<div class="container">
  <% if @studio.photos.length > 1%>
    <div class="carouselle d-flex justify-content-center">
      <div id="carouselExampleIndicators" class="carousel slide input-group w-50" data-bs-ride="carousel">
        <div class="carousel-indicators">
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
          <% @studio.photos.each do |photo| %>
              <div class="carousel-item <%= 'active' if @studio.photos.index(photo) == 0 %>">
                <%= cl_image_tag photo.key, class: 'w-100' %>
              </div>
            <% end %>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    </div>
  <%end %>
</div>

<%# --------------------------- FORM BOOKING STUDIO ------------------------- %>
<div class="container p-5 d-flex align-items-center justify-content-between border m-5">
  <%# -------- partie formulaire ------------- %>
  <div class="w-50 ms-5 me-5">
    <h2 class="text-center">Book a session </h2>
    <% if @booking.nil? %>
      <% @booking = Booking.new %>
    <% end %>
    <%= simple_form_for [@studio, @booking], html: {data: {controller: 'flatpickr' }} do |f| %>
    <div data-flatpickr-target= "date" data-bookings = "<%= @dates.to_json%>" ></div>
      <%= f.input :start_date, as: :string, required: true, input_html: {data:{target: 'start_date'}, class: "datepicker"} %>
      <%= f.input :end_date, as: :string, required: true, input_html: {data:{target: 'end_date'}, class: "datepicker", id: 'enddate'} %>
      <%= f.input :comment %>
      <% if current_user != @studio.user %>
        <%= f.submit class:"btn btn-blue mt-2 d-grid gap-2 col-6 mx-auto" %>
      <% else %>
        <p style="font-size:12px;">This is your studio, no need to book, you can use it when it is available</p>
      <% end %>
    <% end %>
  </div>


  <%# -------- partie bookings ------------- %>
<%# -- SEULEMENT LE PROPRIETAIRE DU STUDIO VOIT LES BOOKINGS -- %>
  <div class="me-5 ms-5">
    <%if  @studio.user == current_user %>
    <p>You have <%= @studio.bookings.length %> bookings for this studio</p>
      <% @studio.bookings.each do |booking| %>
        <%= link_to profile_path(current_user), style:"text-decoration:none;" do %>
          <div class="card-booking">
            <h3 style="color:black;"> You have a booking from <%= booking.user.nickname %></h3>
          </div>
        <% end %>
      <% end%>
    <%end %>
  </div>

<%# -- SEULEMENT LA PERSONNE QUI BOOK VOIT SON BOOKINGS -- %>
  <div class="me-5">
    <% @studio.bookings.each do |booking| %>
      <% if booking.user == current_user %>
        <div class="card-booking">
          <h3 style="color:black;"> You booked this studio =>   </h3>
          <h3 style="color:black;"> from <%= booking.start_date %> to <%= booking.end_date %> </h3>
          <%# mettre un link to delete et linkto profile ? %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>


<%# ----------------------------- debut reviews ----------------------------------- %>
<div class="container mt-5">
  <div class="d-flex align-items-center justify-content-between">
      <div>
      <% if @studio.reviews.blank? %>
      <p></p>
      <% else %>
      <h3>Reviews</h3>
      <p>Moyenne : <%= @average2 %></p>
      <% end %>
      <% unless @studio.reviews.blank? %>
        <% @studio.reviews.each do |review| %>
        <%= link_to profile_path(review.user.id) do %>
          <img class="avatar-square" src="<%=review.user.photo_id_url%>" alt="">
        <% end %>
        <p>
          <% Review::AUTHORIZED_RATINGS.each do |number| %>
            <i class="fa<%= (number > review.rating) ? 'r' : 's' %> fa-star"></i>
          <% end %>
          <%= review.comment %>
        </p>
        <% end %>
    <% end %>
    </div>

    <% if current_user != @studio.user %>
      <div class="w-50">
        <h2>Leave Feedback after your stay :</h2>
        <% if @review.nil? %>
          <% @review = Review.new %>
        <% end %>
        <%= simple_form_for [@studio, @review] do |f| %>
        <%= f.input :comment %>
        <%= f.input :rating, as: :hidden  %>
        <div class="my-3">
          <% Review::AUTHORIZED_RATINGS.each do |index| %>
            <i id="<%= index %>" class="review-rating far fa-star"></i>
          <% end %>
        </div>
        <%= f.submit class: "btn btn-blue", value: "Validate" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>


<%# ---------------------------- BOUTONS ET LIENS -------------------------- %>
<div class="basdepage mt-5 ms-5">
  <p class="btn-white-undo"> Back Home
  <%= link_to studios_path, class: "text-dark" do %>
    <i class="fas fa-undo"></i>
  <% end %>
  </p>
  <% if policy(@studio).edit? %>
    <%= link_to 'Edit studio', edit_studio_path(@studio), class:"btn-blue mb-3" %>
  <% end %>
  <% if policy(@studio).destroy? %>
    <%= link_to 'Delete studio', studio_path(@studio), class:"btn-red",
    method: :delete, data: { confirm: "Are you sure?" } %>
  <% end %>
</div>